# Generated by Django 3.2.16 on 2022-12-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('lr_video_name', models.CharField(max_length=50)),
                ('lr_video_path', models.CharField(max_length=100)),
                ('lr_video_time', models.CharField(max_length=100)),
                ('hr_video_name', models.CharField(max_length=50)),
                ('hr_video_path', models.CharField(max_length=100)),
                ('hr_video_time', models.CharField(max_length=100)),
            ],
        ),
    ]
