# Generated by Django 4.1 on 2024-04-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_user_id', models.IntegerField()),
                ('upload_time', models.DateTimeField(verbose_name='uploading time')),
                ('is_collection', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('lr_video_path', models.CharField(max_length=150)),
                ('hr_video_path', models.CharField(max_length=150)),
                ('image_path', models.CharField(max_length=150)),
            ],
        ),
    ]
