# Generated by Django 3.2.16 on 2022-12-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doublevideo',
            old_name='user_name',
            new_name='user_id',
        ),
    ]
