# Generated by Django 3.2.16 on 2022-12-16 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_user_name_doublevideo_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doublevideo',
            name='hr_video_time',
        ),
        migrations.RemoveField(
            model_name='doublevideo',
            name='lr_video_time',
        ),
        migrations.AddField(
            model_name='doublevideo',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doublevideo',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 4, 35, 59, 99912, tzinfo=utc), verbose_name='uploading time'),
        ),
        migrations.AlterField(
            model_name='doublevideo',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
