# Generated by Django 3.2.16 on 2022-12-16 04:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20221216_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublevideo',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 4, 36, 7, 214464, tzinfo=utc), verbose_name='uploading time'),
        ),
    ]
