# Generated by Django 4.1 on 2024-04-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_doublevideo_name_alter_doublevideo_lr_video_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doublevideo',
            name='hr_video_name',
        ),
        migrations.RemoveField(
            model_name='doublevideo',
            name='lr_video_name',
        ),
        migrations.AlterField(
            model_name='doublevideo',
            name='hr_video_path',
            field=models.CharField(max_length=150),
        ),
    ]
